// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Dataset struct {
	ID                  pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	Label               pgtype.Text
	Seed                int64
	RowsRequested       int32
	GenderFilter        pgtype.Text
	MaritalStatusFilter pgtype.Text
	SalaryMin           pgtype.Numeric
	SalaryMax           pgtype.Numeric
	AgeMin              pgtype.Int4
	AgeMax              pgtype.Int4
}

type Person struct {
	ID              pgtype.UUID
	DatasetID       pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	FirstName       string
	MiddleName      pgtype.Text
	LastName        string
	Gender          pgtype.Text
	MaritalStatus   pgtype.Text
	Age             pgtype.Int4
	WeightLbs       pgtype.Int4
	Occupation      pgtype.Text
	OccupationalPay pgtype.Numeric
	City            pgtype.Text
	State           pgtype.Text
	ZipCode         pgtype.Text
	CollegeType     pgtype.Text
	CollegeDegree   pgtype.Text
	CollegeLocation pgtype.Text
}
